echo Press ctrl-E to quit
echo Keyboard controls from vc8e program:
echo Player 1  Player 2  Command
echo 1         9         fire weapon
echo 2         0         rotate CCW
echo 3         -         rotate CW
echo 4         =         thrusters
echo Press both rotate keys simulatenously to warp into hyperspace
echo Type 'o' in PDP-8 emulator window to get a list of features
l ../imagefiles/spacewar/spacewar.bin
at ttix 2222
set ttox0 8b

g 200
