#!/bin/bash
~/src/autosetup/autosetup --install || exit 1
chmod -x         $(fossil status --meta    autosetup | grep ^EXEC | cut -c8-)
fossil rm --hard $(fossil status --missing autosetup | grep ^MISS | cut -c8-)
fossil add autosetup/*
