#!/bin/bash
# bosi3 - The Binary OS Image creation/update scripts, #3
#
# This script shrinks the filesystem on the SD card we're about to
# image to just a bit bigger than required to hold its present
# contents.
#
# The extra 100 megs in the arithmetic below accounts for the /boot
# partition, since the `resizepart` command takes a partition end value,
# not a size value.
#
# We don't calculate the actual end of the /boot partition and use that
# value because we want a bit of slack space to buy time for an end user
# who neglects to expand the card image into the free space available on
# their SD card after first boot.

set -e

sudo umount /dev/sda2 || true		# might auto-mount, might not
sudo e2fsck -f /dev/sda2			# resize2fs demands it
blocks=$(sudo resize2fs -M /dev/sda2 | tail -1 | grep -o '[0-9]\+')
if [ "$blocks" -gt 0 ]
then
	sudo parted /dev/sda resizepart 2 $(($blocks * 4096 + 10**8))b
	sudo resize2fs /dev/sda2		# take any slack back up
else
	echo "Failed to extract new filesystem size from resize2fs!"
	echo
	exit 1
fi
