#!/bin/bash
# bosi4 - The Binary OS Image creation/update scripts, #4
#
# This script images the SD card in a USB reader on a Mac OS X box.

set -e

if [ -n "$1" ]
then
	blocks="$1"
	shift
	. $(dirname "$0")/../etc/bosi-vals "$@"

	sudo diskutil unmountDisk $rdisk		# it auto-mounted
	sudo dd if=$rdisk bs=4k count=$blocks of=$img
	zip -9j $img.zip $img
	# rm $img happens in bosi5
else
	cat <<USAGE
usage: $0 <blocks> [tag]
    
    The 'blocks' value is given at the end of the bosi3 script.
    
    The 'tag' value defaults to 'all', but may be 'nls' or similar to
    mark alternate binary OS image types.

USAGE
	exit 1
fi
