#!/bin/bash
# bosi1 - The Binary OS Image creation/update scripts, #1
#
# This script initiates the creation/update of the binary OS images
# the SD card.

nu=pidp8i
nh=/home/$nu
repo=pidp8i
branch=release
test -n "$1" && branch="$1"

set -e

if [ "$USER" != "root" ]
then
	echo "You need to be root for this script to work."
	echo "Really root, I mean, not sudo'd up."
	echo
	exit 1
fi

if getent passwd $nu > /dev/null
then
	cd $HOME
else
	sudo usermod \
		-d $nh \
		-l $nu \
		-p $(openssl passwd -1 edsonDeCastro1968) \
		-m pi 
	cd $nh
fi

sudo apt update && sudo apt upgrade

test -n "$(type -p fossil)" || sudo apt install fossil

if [ ! -d museum ]
then
	mkdir -p museum $repo
	fossil clone https://tangentsoft.com/$repo museum/$repo.fossil
fi

cd $repo

if [ -r ChangeLog.md ]
then
	fossil revert			# just in case
	fossil update $branch
else
	fossil open ~/museum/$repo.fossil $branch
	./configure
fi

make
sudo make install
make clean
sudo reboot
