#!/bin/bash -x
# bosi - The Binary OS Image creation/update script
#
# Copyright © 2016-2017 by Warren Young
# 
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS LISTED ABOVE BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
# THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# 
# Except as contained in this notice, the names of the authors above shall
# not be used in advertising or otherwise to promote the sale, use or
# other dealings in this Software without prior written authorization from
# those authors.

verb="$1"
tag="$2"
test -z "$tag" && tag=ils

nu=pidp8i
nh=/home/$nu
repo=pidp8i
dldir="$HOME/tangentsoft.com/dl"
os=jessie-lite
img=$dldir/pidp8i-$(date +%Y.%m.%d)-$tag-$os.img
greadlink=$(type -p greadlink || type -p readlink)
this=$($greadlink -f $0)
topdir="$($greadlink -f "$(dirname "$this")"/..)"


# Initial steps
function do_init() {
	sudo apt-get update && sudo apt-get -y upgrade || true

	test "$USER" = "root" && exec sudo -i -u $nu $nh/bosi init
	cd $HOME

	test -n "$(type -p fossil)" || sudo apt-get -y install fossil
	test -f /usr/include/curses.h || sudo apt-get -y install libncurses-dev

	if [ ! -d museum ]
	then
		mkdir -p museum $repo
		fossil clone https://tangentsoft.com/$repo museum/$repo.fossil
	fi

	cd $repo

	if [ -r ChangeLog.md ]
	then
		fossil revert			# just in case
		fossil update release
	else
		fossil open ~/museum/$repo.fossil release
		./configure
	fi

	tools/mmake
	sudo make install || true
	sudo reboot
}


# This script resets the OS's configuration to a clean first boot state.
function do_reset() {
	if [ "$USER" != "root" ]
	then
		echo "The reset step has to be run as root.  The explanation is"
		echo "given in the section for 'reset' in RELEASE-PROCESS.md."
		echo
		exit 1
	fi

	history -c ; rm -f ~/.bash_history
	test "$USER" = "root" || exec sudo $this reset

	shred -u /etc/ssh/*key* || true             # allow multiple resets
	dphys-swapfile uninstall || true
	dd if=/dev/zero of=/junk bs=1M || true		# it *will* error-out!
	rm -f /junk
	encpass=$(openssl passwd -1 edsonDeCastro1968)
	if [ -e "$nh" ]
	then
		# A prior pass already renamed the default user and moved its
		# home directory, so just change the password.
		usermod -p $encpass pidp8i
	else
		# First pass on a clean SD card: rename 'pi' user to 'pidp8i'
		# and move its home directory.  Must shut simulator down first
        # else user "pi" will still be in use.
        systemctl stop pidp8i
		usermod -d $nh -l $nu -p $encpass -m pi 
	fi
	passwd -e pidp8i
	poweroff
}


# Shrink the filesystem on the OS SD card we're about to image to just a
# bit bigger than required to hold its present contents.
#
# The extra 100 megs in the arithmetic below accounts for the /boot
# partition, since the `resizepart` command takes a partition end value,
# not a size value.
#
# We don't calculate the actual end of the /boot partition and use that
# value because we want a bit of slack space to buy time for an end user
# who neglects to expand the card image into the free space available on
# their SD card after first boot.
function do_shrink() {
	test "$USER" = "root" || exec sudo $this shrink

	umount /dev/sda2 || true	# might auto-mount, might not
	e2fsck -f /dev/sda2			# resize2fs demands it

    # Pack it down tight
	blocks=$(
		resize2fs -M /dev/sda2 2>&1 |
		grep 'blocks long' | 
		grep -wo '[0-9]\+'
	)
	if [ "$blocks" -gt 0 ]
	then
        # And now give it a bit of breathing room
		parted /dev/sda resizepart 2 $(($blocks * 4096 + 10**8))b
        resize2fs /dev/sda2
        poweroff
	else
		echo "Failed to extract new filesystem size from resize2fs!"
		echo
		exit 1
	fi
}


# This script images the OS SD card in a USB reader on a Mac OS X box.
function do_image() {
	set +x
    while read line
    do
        case $line in
            /dev/*)
                dev=$(echo $line | cut -f1 -d' ')
                ;;

            0:*)
                case $line in
                    *FDisk_partition_scheme*) ;;
                    *) dev= ;;		# can't be the OS SD card
                esac
                ;;

            1:*)
                case $line in
                    *Windows_FAT_32\ boot*) ;;
                    *) dev= ;;		# can't be the OS SD card
                esac
                ;;

            2:*)
                case $line in
                    *Linux\ Untitled*) break ;;	# found it!
                    *) dev= ;;		# can't be the OS SD card
                esac
                ;;
        esac
    done < <(diskutil list)

    if [ -z "$dev" ]
    then
        echo "Failed to find OS SD card!"
        echo
        exit 1
    fi

    echo
    echo "-------------------------------------------------------"
    diskutil info "$dev"
    echo "-------------------------------------------------------"
    echo
    read -p "Is that the OS SD card? [y/N]: " answer
    case $answer in
        [Yy]*) ;;
        *) exit 1
    esac

    mf=/tmp/MANIFEST.txt
    readme=/tmp/README.md
    cp "$topdir/doc/OS-images.md" $readme
    set -x
    diskutil unmountDisk $dev	    	# it auto-mounted
    sudo dd if=$dev bs=1m of=$img
    echo -e 'SHA256 hash and size of included *.img file:\n' >> $mf
    shasum -a 256 $img >> $mf
    wc -c $img >> $mf
    imgdir="$(dirname "$img")"
    sed -i '' -e "s_$imgdir/__" "$mf"   # nix local paths in manifest
    unix2dos $mf                        # might be opened on Windows
    zip -9j $img.zip $img $mf $readme
    rm -f $mf $readme

    sudo dd if=/dev/zero of=$dev bs=1m  # ensure a clean test
    sudo dd if=$img of=$dev bs=1m
    diskutil unmountDisk $dev || true	# Paragon ExtFS might be installed
}


# Clean up after the above
function do_finish() {
	rmtrash $img
	cd $dldir/..
	make synch
}


# Display the usage message
function usage() {
	cat <<USAGE
usage: $0 <verb> [tag]

    The available verbs are init, reset, shrink, image, and finish.

    You may include a tag parameter with the 'image' and 'finish' verbs
    to override the default tag ('ils') used in image and zip file
    outputs.

    See RELEASE-PROCESS.md for more info.

USAGE
	exit 1
}


# Main routine
set -e
case "$verb" in
	in*) do_init ;;
	re*) do_reset ;;
	sh*) do_shrink ;;
	im*) do_image ;;
	fi*) do_finish ;;
	*)   usage ;;
esac
