#!/bin/bash
sys="$(uname -s)"
if [ -r /proc/cpuinfo ]
then
	# It's a Linux box
	grep -Ec '^processor\s+:' /proc/cpuinfo
elif [ "$sys" = "Darwin" -o "$sys" = "FreeBSD" -o "$sys" = "OpenBSD" -o "$sys" = "NetBSD" ]
then
	# It's a macOS or BSD box
	/usr/sbin/sysctl -n hw.ncpu
else
	# No known way to find out, so report only 1 core
	echo 1
fi
