#! /bin/bash

# Program to decompress, cut apart and compare the contents the
# "last" and "fail" lzw files made by test-os8-run.
# Run from the current working directory.

if [ ! -f last.rklz ]; then
    echo "last.rklz not found."
    exit -1
fi

if [ ! -f fail.rklz ]; then
    echo "fail.rklz not found."
    exit -1
fi

lz4 -dq last.rklz last.rk05
lz4 -dq fail.rklz fail.rk05

mkdir rka_last rkb_last rka_fail rkb_fail

echo "unpack 1 of 4: last rka"
../../bin/os8-cp -rk0s last.rk05 -i RKA0:*.* rka_last/
echo "unpack 2 of 4: last rkb:"
../../bin/os8-cp -rk0s last.rk05 -i RKB0:*.* rkb_last/
echo "unpack 3 of 4: fail rka"
../../bin/os8-cp -rk0s fail.rk05 -i RKA0:*.* rka_fail/
echo "unpack 4 of 4: fail rkb"
../../bin/os8-cp -rk0s fail.rk05 -i RKB0:*.* rkb_fail/

diff rka_last rka_fail
diff rkb_last rkb_fail
