#!/bin/bash
/Applications/calibre.app/Contents/MacOS/ebook-convert \
    doc/manual.md doc/manual.pdf \
    --pdf-mono-family  'Source Code Pro' \
    --pdf-sans-family  'Myriad Pro' \
    --pdf-serif-family 'Adobe Garamond Pro' \
    --page-breaks-before / \
    --extra-css doc/pdf.css &&
    fossil uv add doc/manual.pdf &&
    fossil uv sync
