#!/bin/bash
########################################################################
# mkrel - Automatically merge trunk changes into the no-lamp-simulator
#   and release branches for a new public release of the software.  Also
#   tags the trunk with the date of release, so old releases can be
#   easily checked out.
#
# Copyright © 2016-2017 Warren Young
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS LISTED ABOVE BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT
# OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# Except as contained in this notice, the names of the authors above
# shall not be used in advertising or otherwise to promote the sale,
# use or other dealings in this Software without prior written
# authorization from those authors.
########################################################################

set -e

tag=v$(date +%Y%m%d)
fossil update &&
	fossil ci --tag $tag -m "Tagged release $tag" &&
	cd ../release &&
	fossil update &&
	fossil merge $tag &&
	! fossil status | grep -q '^CONFLICT' &&
	tools/mmake &&
	fossil diff -w | less &&
	fossil ci -m "Merged trunk changes for $tag into release branch" &&
	cd ../no-lamp-simulator &&
	fossil update &&
	fossil merge release &&
	! fossil status | grep -q '^CONFLICT' &&
	tools/mmake &&
	fossil diff -w | less &&
	fossil ci -m "Merged release $tag changes in"
