#!/bin/bash -e
lr=/usr/bin/lsb_release
if [ -x $lr ]
then
    vs=$(lsb_release -sicr | tr '\n' - | tr '[A-Z]' '[a-z]' | sed -e 's/-$//')
    d=fossil-$vs
    cp /usr/local/bin/fossil $d
    fossil uv add $d
    fossil uv sync
    rm $d
else
    echo Could not find $lr!
fi
